apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-salesforce
spec:
  selector:
    matchLabels:
      app: ms-salesforce-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-salesforce-app
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: bigquery-key
      containers:
        # [START esp]
        - name: ms-salesforce-esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          resources:
            requests:
              memory: 100Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          args:
            [
              "--http_port=8081",
              "--backend=127.0.0.1:8080",
              "--service=ms-salesforce.endpoints.terpel-gtic-datalake.cloud.goog",
              "--rollout_strategy=managed",
              "--healthz=healthz",
            ]
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
          # [END esp]
          ports:
            - containerPort: 8081
        - name: ms-salesforce-cont
          image: gcr.io/terpel-gtic-datalake/ms-salesforce:0.0.5
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          resources:
            requests:
              memory: 100Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json 
          - name: BIGQUERY_GCP_PROJECT
            value: terpel-gtic-datalake 
          - name: GOOGLE_STORAGE_BUCKET
            value: terpel_config_diccionario_datalake
          - name: GCS_CONFIG_FILE
            value: diccionario.salesforce.json
          - name: SQL_USER
            valueFrom: 
              secretKeyRef: 
                key: username
                name: database-mysql-cred
          - name: SQL_PWD
            valueFrom: 
              secretKeyRef: 
                key: password
                name: database-mysql-cred
          - name: SQL_PORT
            value: '3306' 
          - name: SQL_IP
            value: '172.28.112.11'
          - name: SQL_DB
            value: db_terpel_datalake_mdm_cruda

