apiVersion: v1
kind: Service
metadata:
  name: ms-salesforce-serv
spec:
  ports:
    - port: 443
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app: ms-salesforce-app
  type: NodePort
